// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/valCurs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MockXMLDaily_AddMockData_FullMethodName    = "/ValCurs.MockXMLDaily/AddMockData"
	MockXMLDaily_DeleteMockData_FullMethodName = "/ValCurs.MockXMLDaily/DeleteMockData"
)

// MockXMLDailyClient is the client API for MockXMLDaily service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// gRPC сервис управления mock cbr.ru/scripts/XML_Daily
type MockXMLDailyClient interface {
	// Добавление mock данных
	AddMockData(ctx context.Context, in *AddValCursRequest, opts ...grpc.CallOption) (*AddValCursResponse, error)
	// Удаление mock данных
	DeleteMockData(ctx context.Context, in *DeleteValCursRequest, opts ...grpc.CallOption) (*DeleteValCursResponse, error)
}

type mockXMLDailyClient struct {
	cc grpc.ClientConnInterface
}

func NewMockXMLDailyClient(cc grpc.ClientConnInterface) MockXMLDailyClient {
	return &mockXMLDailyClient{cc}
}

func (c *mockXMLDailyClient) AddMockData(ctx context.Context, in *AddValCursRequest, opts ...grpc.CallOption) (*AddValCursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddValCursResponse)
	err := c.cc.Invoke(ctx, MockXMLDaily_AddMockData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mockXMLDailyClient) DeleteMockData(ctx context.Context, in *DeleteValCursRequest, opts ...grpc.CallOption) (*DeleteValCursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteValCursResponse)
	err := c.cc.Invoke(ctx, MockXMLDaily_DeleteMockData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockXMLDailyServer is the server API for MockXMLDaily service.
// All implementations must embed UnimplementedMockXMLDailyServer
// for forward compatibility.
//
// gRPC сервис управления mock cbr.ru/scripts/XML_Daily
type MockXMLDailyServer interface {
	// Добавление mock данных
	AddMockData(context.Context, *AddValCursRequest) (*AddValCursResponse, error)
	// Удаление mock данных
	DeleteMockData(context.Context, *DeleteValCursRequest) (*DeleteValCursResponse, error)
	mustEmbedUnimplementedMockXMLDailyServer()
}

// UnimplementedMockXMLDailyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMockXMLDailyServer struct{}

func (UnimplementedMockXMLDailyServer) AddMockData(context.Context, *AddValCursRequest) (*AddValCursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMockData not implemented")
}
func (UnimplementedMockXMLDailyServer) DeleteMockData(context.Context, *DeleteValCursRequest) (*DeleteValCursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMockData not implemented")
}
func (UnimplementedMockXMLDailyServer) mustEmbedUnimplementedMockXMLDailyServer() {}
func (UnimplementedMockXMLDailyServer) testEmbeddedByValue()                      {}

// UnsafeMockXMLDailyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockXMLDailyServer will
// result in compilation errors.
type UnsafeMockXMLDailyServer interface {
	mustEmbedUnimplementedMockXMLDailyServer()
}

func RegisterMockXMLDailyServer(s grpc.ServiceRegistrar, srv MockXMLDailyServer) {
	// If the following call pancis, it indicates UnimplementedMockXMLDailyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MockXMLDaily_ServiceDesc, srv)
}

func _MockXMLDaily_AddMockData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddValCursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockXMLDailyServer).AddMockData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockXMLDaily_AddMockData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockXMLDailyServer).AddMockData(ctx, req.(*AddValCursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MockXMLDaily_DeleteMockData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteValCursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockXMLDailyServer).DeleteMockData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MockXMLDaily_DeleteMockData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockXMLDailyServer).DeleteMockData(ctx, req.(*DeleteValCursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MockXMLDaily_ServiceDesc is the grpc.ServiceDesc for MockXMLDaily service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MockXMLDaily_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ValCurs.MockXMLDaily",
	HandlerType: (*MockXMLDailyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMockData",
			Handler:    _MockXMLDaily_AddMockData_Handler,
		},
		{
			MethodName: "DeleteMockData",
			Handler:    _MockXMLDaily_DeleteMockData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/valCurs.proto",
}
