syntax = "proto3";

option go_package = "./proto;proto";

package ValCurs;

// gRPC сервис управления mock cbr.ru/scripts/XML_Daily
service MockXMLDaily {
  // Добавление mock данных
  rpc AddMockData(AddValCursRequest) returns (AddValCursResponse);
  // Удаление mock данных
    rpc DeleteMockData(DeleteValCursRequest) returns (DeleteValCursResponse);
  // Очистка всех данных (reset)
}

// ValCurs
message ValCurs {
  string date = 1; // формат: "02.01.2006" 
  string name = 2;
  repeated Valute valutes = 3;
}

// Valute
message Valute {
  string id = 1;
  int32 num_code = 2;
  string char_code = 3;
  int32 nominal = 4;
  string name = 5;
  double value = 6;
  double vunit_rate = 7;
}

// Requests & Responses

//  AddValCurs
message AddValCursRequest {
  int32 httpStatus = 1; 
  ValCurs valCurs = 2;
}

message AddValCursResponse {
  string message = 1;
}

// DeleteValCurs
message DeleteValCursRequest {
  string date = 1;
}

message DeleteValCursResponse {
  string message = 1;
}