// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/valCurs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValCurs
type ValCurs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // формат: "02.01.2006"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Valutes       []*Valute              `protobuf:"bytes,3,rep,name=valutes,proto3" json:"valutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValCurs) Reset() {
	*x = ValCurs{}
	mi := &file_proto_valCurs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValCurs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValCurs) ProtoMessage() {}

func (x *ValCurs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValCurs.ProtoReflect.Descriptor instead.
func (*ValCurs) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{0}
}

func (x *ValCurs) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ValCurs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValCurs) GetValutes() []*Valute {
	if x != nil {
		return x.Valutes
	}
	return nil
}

// Valute
type Valute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NumCode       int32                  `protobuf:"varint,2,opt,name=num_code,json=numCode,proto3" json:"num_code,omitempty"`
	CharCode      string                 `protobuf:"bytes,3,opt,name=char_code,json=charCode,proto3" json:"char_code,omitempty"`
	Nominal       int32                  `protobuf:"varint,4,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,6,opt,name=value,proto3" json:"value,omitempty"`
	VunitRate     float64                `protobuf:"fixed64,7,opt,name=vunit_rate,json=vunitRate,proto3" json:"vunit_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Valute) Reset() {
	*x = Valute{}
	mi := &file_proto_valCurs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Valute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Valute) ProtoMessage() {}

func (x *Valute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Valute.ProtoReflect.Descriptor instead.
func (*Valute) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{1}
}

func (x *Valute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Valute) GetNumCode() int32 {
	if x != nil {
		return x.NumCode
	}
	return 0
}

func (x *Valute) GetCharCode() string {
	if x != nil {
		return x.CharCode
	}
	return ""
}

func (x *Valute) GetNominal() int32 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *Valute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Valute) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Valute) GetVunitRate() float64 {
	if x != nil {
		return x.VunitRate
	}
	return 0
}

// AddValCurs
type AddValCursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpStatus    int32                  `protobuf:"varint,1,opt,name=httpStatus,proto3" json:"httpStatus,omitempty"`
	ValCurs       *ValCurs               `protobuf:"bytes,2,opt,name=valCurs,proto3" json:"valCurs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddValCursRequest) Reset() {
	*x = AddValCursRequest{}
	mi := &file_proto_valCurs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddValCursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddValCursRequest) ProtoMessage() {}

func (x *AddValCursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddValCursRequest.ProtoReflect.Descriptor instead.
func (*AddValCursRequest) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{2}
}

func (x *AddValCursRequest) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *AddValCursRequest) GetValCurs() *ValCurs {
	if x != nil {
		return x.ValCurs
	}
	return nil
}

type AddValCursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddValCursResponse) Reset() {
	*x = AddValCursResponse{}
	mi := &file_proto_valCurs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddValCursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddValCursResponse) ProtoMessage() {}

func (x *AddValCursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddValCursResponse.ProtoReflect.Descriptor instead.
func (*AddValCursResponse) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{3}
}

func (x *AddValCursResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeleteValCurs
type DeleteValCursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValCursRequest) Reset() {
	*x = DeleteValCursRequest{}
	mi := &file_proto_valCurs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValCursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValCursRequest) ProtoMessage() {}

func (x *DeleteValCursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValCursRequest.ProtoReflect.Descriptor instead.
func (*DeleteValCursRequest) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteValCursRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type DeleteValCursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteValCursResponse) Reset() {
	*x = DeleteValCursResponse{}
	mi := &file_proto_valCurs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteValCursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteValCursResponse) ProtoMessage() {}

func (x *DeleteValCursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_valCurs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteValCursResponse.ProtoReflect.Descriptor instead.
func (*DeleteValCursResponse) Descriptor() ([]byte, []int) {
	return file_proto_valCurs_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteValCursResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_valCurs_proto protoreflect.FileDescriptor

const file_proto_valCurs_proto_rawDesc = "" +
	"\n" +
	"\x13proto/valCurs.proto\x12\aValCurs\"\\\n" +
	"\aValCurs\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\avalutes\x18\x03 \x03(\v2\x0f.ValCurs.ValuteR\avalutes\"\xb3\x01\n" +
	"\x06Valute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnum_code\x18\x02 \x01(\x05R\anumCode\x12\x1b\n" +
	"\tchar_code\x18\x03 \x01(\tR\bcharCode\x12\x18\n" +
	"\anominal\x18\x04 \x01(\x05R\anominal\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"vunit_rate\x18\a \x01(\x01R\tvunitRate\"_\n" +
	"\x11AddValCursRequest\x12\x1e\n" +
	"\n" +
	"httpStatus\x18\x01 \x01(\x05R\n" +
	"httpStatus\x12*\n" +
	"\avalCurs\x18\x02 \x01(\v2\x10.ValCurs.ValCursR\avalCurs\".\n" +
	"\x12AddValCursResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"*\n" +
	"\x14DeleteValCursRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\"1\n" +
	"\x15DeleteValCursResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa7\x01\n" +
	"\fMockXMLDaily\x12F\n" +
	"\vAddMockData\x12\x1a.ValCurs.AddValCursRequest\x1a\x1b.ValCurs.AddValCursResponse\x12O\n" +
	"\x0eDeleteMockData\x12\x1d.ValCurs.DeleteValCursRequest\x1a\x1e.ValCurs.DeleteValCursResponseB\x0fZ\r./proto;protob\x06proto3"

var (
	file_proto_valCurs_proto_rawDescOnce sync.Once
	file_proto_valCurs_proto_rawDescData []byte
)

func file_proto_valCurs_proto_rawDescGZIP() []byte {
	file_proto_valCurs_proto_rawDescOnce.Do(func() {
		file_proto_valCurs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_valCurs_proto_rawDesc), len(file_proto_valCurs_proto_rawDesc)))
	})
	return file_proto_valCurs_proto_rawDescData
}

var file_proto_valCurs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_valCurs_proto_goTypes = []any{
	(*ValCurs)(nil),               // 0: ValCurs.ValCurs
	(*Valute)(nil),                // 1: ValCurs.Valute
	(*AddValCursRequest)(nil),     // 2: ValCurs.AddValCursRequest
	(*AddValCursResponse)(nil),    // 3: ValCurs.AddValCursResponse
	(*DeleteValCursRequest)(nil),  // 4: ValCurs.DeleteValCursRequest
	(*DeleteValCursResponse)(nil), // 5: ValCurs.DeleteValCursResponse
}
var file_proto_valCurs_proto_depIdxs = []int32{
	1, // 0: ValCurs.ValCurs.valutes:type_name -> ValCurs.Valute
	0, // 1: ValCurs.AddValCursRequest.valCurs:type_name -> ValCurs.ValCurs
	2, // 2: ValCurs.MockXMLDaily.AddMockData:input_type -> ValCurs.AddValCursRequest
	4, // 3: ValCurs.MockXMLDaily.DeleteMockData:input_type -> ValCurs.DeleteValCursRequest
	3, // 4: ValCurs.MockXMLDaily.AddMockData:output_type -> ValCurs.AddValCursResponse
	5, // 5: ValCurs.MockXMLDaily.DeleteMockData:output_type -> ValCurs.DeleteValCursResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_valCurs_proto_init() }
func file_proto_valCurs_proto_init() {
	if File_proto_valCurs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_valCurs_proto_rawDesc), len(file_proto_valCurs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_valCurs_proto_goTypes,
		DependencyIndexes: file_proto_valCurs_proto_depIdxs,
		MessageInfos:      file_proto_valCurs_proto_msgTypes,
	}.Build()
	File_proto_valCurs_proto = out.File
	file_proto_valCurs_proto_goTypes = nil
	file_proto_valCurs_proto_depIdxs = nil
}
