// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "text/xml"
    ],
    "produces": [
        "text/xml"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/curs": {
            "get": {
                "description": "Возвращает XML-список валют на заданную дату и по заданному имени источника. Дата и имя берутся из внутреннего состояния, которое можно изменить через gRPC SetState.",
                "produces": [
                    "text/xml"
                ],
                "tags": [
                    "currency"
                ],
                "summary": "Получить валютные курсы по дате и имени источника",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ValCursDTO"
                        }
                    },
                    "500": {
                        "description": "Ошибка запроса",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ValCursDTO": {
            "description": "The structure of the response with foreign exchange rates for the specified date and name.",
            "type": "object",
            "properties": {
                "date": {
                    "description": "Source Date",
                    "type": "string",
                    "example": "02.01.2006"
                },
                "name": {
                    "description": "Source name",
                    "type": "string",
                    "example": "Foreign Currency Market"
                },
                "valutes": {
                    "description": "List of currencies",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ValuteDTO"
                    }
                }
            }
        },
        "dto.ValuteDTO": {
            "description": "information about the currency and its course.",
            "type": "object",
            "properties": {
                "charCode": {
                    "description": "Lamp currency code (ISO 4217)",
                    "type": "string",
                    "example": "USD"
                },
                "id": {
                    "description": "Currency identifier",
                    "type": "string",
                    "example": "R01235"
                },
                "name": {
                    "description": "Name of the currency",
                    "type": "string",
                    "example": "Доллар США"
                },
                "nominal": {
                    "description": "Nominal",
                    "type": "string",
                    "example": "1"
                },
                "numCode": {
                    "description": "Numerical currency code (ISO 4217)",
                    "type": "string",
                    "example": "840"
                },
                "value": {
                    "description": "Course value",
                    "type": "string",
                    "example": "30,9436"
                },
                "vunitRate": {
                    "description": "Course per unit of currency",
                    "type": "string",
                    "example": "30,9436"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "OzonTest",
	Description:      "Мок-сервис получения курсов валют с сайта cbr.ru в XML-формате.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
